import snapshot from '@/data/partner-node-workflows.snapshot.json';

/**
 * Which hub workflows call a paid partner (API-backed) node.
 *
 * The site claims a free run wherever a workflow is not marked as using partner
 * nodes, and that mark was previously the hand-applied `API` tag alone. Tagging
 * is manual, so 103 approved workflows that call OpenAI, Gemini, ByteDance and
 * others carried no tag and advertised "Try free on Comfy Cloud" for a run that
 * charges credits.
 *
 * This snapshot is the second half of that signal, generated by
 * `pnpm partner-nodes:refresh-snapshot`. It is a committed snapshot, so it goes
 * stale as workflows are published; the tag still catches anything it misses,
 * and the durable fix is the hub deriving the tag at publish time.
 */

const PARTNER_NODE_SHARE_IDS: ReadonlySet<string> = new Set(snapshot.shareIds);

/** Whether a workflow is known to call a paid partner node. */
export function usesPartnerNodes(shareId: string | undefined | null): boolean {
  return !!shareId && PARTNER_NODE_SHARE_IDS.has(shareId);
}

/**
 * Whether a workflow should be presented as billable rather than free.
 *
 * Either signal is enough: the curated `API` tag, or a partner node found in the
 * workflow itself. They cover different gaps, so both are checked.
 */
export function isBillableWorkflow(
  tags: string[] | undefined | null,
  shareId: string | undefined | null
): boolean {
  return (tags?.includes('API') ?? false) || usesPartnerNodes(shareId);
}

/** Snapshot freshness, for diagnostics. */
export const PARTNER_NODE_SNAPSHOT_META = {
  fetchedAt: snapshot.fetchedAt,
  apiNodeCount: snapshot.apiNodeCount,
  workflowCount: snapshot.shareIds.length,
};
