import snapshot from '@/data/partner-node-workflows.snapshot.json';

/**
 * Which hub workflows call a paid partner (API-backed) node.
 *
 * The site claims a free run wherever a workflow is not marked as using partner
 * nodes, and that mark was previously the hand-applied `API` tag alone. Tagging
 * is manual, so approved workflows calling OpenAI, Gemini, ByteDance and others
 * carried no tag and advertised "Try free on Comfy Cloud" for a run that charges
 * credits.
 *
 * The snapshot is generated by `pnpm partner-nodes:refresh-snapshot`. It records
 * two lists, and the second one matters as much as the first:
 *
 * - `shareIds`: workflows found to call a partner node.
 * - `scannedShareIds`: every workflow the run actually inspected.
 *
 * A committed snapshot goes stale the moment something new is published, so
 * absence from `shareIds` is not evidence of anything on its own. Only a workflow
 * that was scanned *and* came back clean can be called free; anything unscanned is
 * unknown and is treated as billable. That way a publish between refreshes
 * under-promises rather than promising a free run it cannot honour.
 */

const PARTNER_NODE_SHARE_IDS: ReadonlySet<string> = new Set(snapshot.shareIds);
const SCANNED_SHARE_IDS: ReadonlySet<string> = new Set(snapshot.scannedShareIds);

/** Whether a workflow is known to call a paid partner node. */
export function usesPartnerNodes(shareId: string | undefined | null): boolean {
  return !!shareId && PARTNER_NODE_SHARE_IDS.has(shareId);
}

/** Whether the snapshot actually inspected this workflow. */
export function wasScannedForPartnerNodes(shareId: string | undefined | null): boolean {
  return !!shareId && SCANNED_SHARE_IDS.has(shareId);
}

/**
 * Whether a workflow should be presented as billable rather than free.
 *
 * Three ways to be billable, and the third is the one that keeps this honest:
 * the curated `API` tag, a partner node found in the workflow, or a workflow the
 * snapshot never saw. Only a scanned, untagged, partner-node-free workflow earns
 * the free claim.
 */
export function isBillableWorkflow(
  tags: string[] | undefined | null,
  shareId: string | undefined | null
): boolean {
  if (tags?.includes('API')) return true;
  if (usesPartnerNodes(shareId)) return true;
  // Unknown to the snapshot, so we cannot vouch for it. Includes anything
  // published since the last refresh.
  return !wasScannedForPartnerNodes(shareId);
}

/** Snapshot freshness, for diagnostics. */
export const PARTNER_NODE_SNAPSHOT_META = {
  fetchedAt: snapshot.fetchedAt,
  apiNodeCount: snapshot.apiNodeCount,
  workflowCount: snapshot.shareIds.length,
  scannedCount: snapshot.scannedShareIds.length,
};
