import snapshot from '@/data/partner-node-workflows.snapshot.json';

/**
 * Which hub workflows call a paid partner (API-backed) node.
 *
 * The site claims a free run wherever a workflow is not marked as using partner
 * nodes, and that mark was previously the hand-applied `API` tag alone. Tagging
 * is manual, so approved workflows calling OpenAI, Gemini, ByteDance and others
 * carried no tag and advertised "Try free on Comfy Cloud" for a run that charges
 * credits.
 *
 * The snapshot is generated by `pnpm partner-nodes:refresh-snapshot`. It records
 * two things, and the second matters as much as the first:
 *
 * - `shareIds`: workflows found to call a partner node.
 * - `scannedAt`: every workflow the run inspected, against the publish date it
 *   had at the time.
 *
 * A committed snapshot goes stale the moment something is published, so absence
 * from `shareIds` is not evidence on its own. Only a workflow scanned *in its
 * current shape* and found clean can be called free; anything else is unknown and
 * treated as billable, so a publish between refreshes under-promises rather than
 * promising a free run it cannot honour.
 *
 * The date is what makes "in its current shape" real. Re-publishing keeps the
 * share id and repoints it at a new version, so an id alone cannot tell you the
 * graph is the one that was scanned.
 */

const PARTNER_NODE_SHARE_IDS: ReadonlySet<string> = new Set(snapshot.shareIds);
const SCANNED_AT: ReadonlyMap<string, string> = new Map(Object.entries(snapshot.scannedAt));

/** Whether a workflow is known to call a paid partner node. */
export function usesPartnerNodes(shareId: string | undefined | null): boolean {
  return !!shareId && PARTNER_NODE_SHARE_IDS.has(shareId);
}

/**
 * Whether the snapshot inspected *this* workflow, as it stands now.
 *
 * A share id is not a stable handle on a graph. Re-publishing keeps the id and
 * repoints it at a new `published_workflow_version`, so a workflow scanned clean
 * can gain a paid node without changing id. Matching the publish date the scan
 * recorded against the one the catalog reports now is what makes "scanned" mean
 * "scanned in this shape".
 *
 * The date is day-granular (the version's create date), so a re-publish later on
 * the same day as a refresh is not detectable here. That residual closes when
 * billability moves to the hub contract.
 */
export function wasScannedForPartnerNodes(
  shareId: string | undefined | null,
  publishedDate: string | undefined | null
): boolean {
  if (!shareId) return false;
  const scannedDate = SCANNED_AT.get(shareId);
  if (scannedDate === undefined) return false;
  // No date to compare means the claim cannot be checked, so it is not made.
  return !!publishedDate && scannedDate === publishedDate;
}

/**
 * Whether a workflow should be presented as billable rather than free.
 *
 * Three ways to be billable, and the third is the one that keeps this honest:
 * the curated `API` tag, a partner node found in the workflow, or a workflow the
 * snapshot never saw. Only a scanned, untagged, partner-node-free workflow earns
 * the free claim.
 */
export function isBillableWorkflow(
  tags: string[] | undefined | null,
  shareId: string | undefined | null,
  publishedDate: string | undefined | null
): boolean {
  if (tags?.includes('API')) return true;
  if (usesPartnerNodes(shareId)) return true;
  // Not vouched for by the snapshot: never scanned, re-published since, or
  // carrying no date to check against.
  return !wasScannedForPartnerNodes(shareId, publishedDate);
}

/** Snapshot freshness, for diagnostics. */
export const PARTNER_NODE_SNAPSHOT_META = {
  fetchedAt: snapshot.fetchedAt,
  apiNodeCount: snapshot.apiNodeCount,
  workflowCount: snapshot.shareIds.length,
  scannedCount: SCANNED_AT.size,
};
