extends: default

rules:
  line-length:
    max: 200  # Allow longer lines in YAML files
  document-start: disable  # Don't require --- at start
  truthy: disable  # Allow on/off instead of true/false