name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: [ "enhancement" ]

body:
- type: markdown
  attributes:
    value: |
      *Please fill this form with as much information as possible, provide screenshots and/or illustrations of the feature if possible*
- type: textarea
  attributes:
    label: Description
    description: 'Please describe the feature in a clear and concise manner.'
- type: textarea
  id: misc
  attributes:
    label: Additional information
    description: Add any other context or screenshots about the feature request here.
