#!/usr/bin/env python3
"""Warn when a catalog diff removes frontend-visible template populations.

This intentionally uses only producer-owned signals already consumed by the
frontend: ``isEssential`` categories and the ``openSource: false`` partner-node
population. It does not attempt to prove that a consumer release is compatible.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

_LIB_DIR = Path(__file__).resolve().parent.parent / "lib"
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

from paths import REPO_ROOT  # noqa: E402

INDEX_PATH = "templates/index.json"
COMMENT_MARKER = "<!-- consumer-catalog-change-check -->"


@dataclass(frozen=True)
class CatalogImpact:
    kind: str
    detail: str


def _essential_populations(index: list[dict]) -> dict[str, int]:
    return {
        str(category.get("title", "")): len(category.get("templates", []))
        for category in index
        if category.get("isEssential") is True and category.get("templates")
    }


def _partner_node_count(index: list[dict]) -> int:
    return sum(
        1
        for category in index
        for template in category.get("templates", [])
        if template.get("openSource") is False
    )


def detect_impacts(before: list[dict], after: list[dict]) -> list[CatalogImpact]:
    """Return consumer-visible populations present before but absent after."""
    impacts: list[CatalogImpact] = []
    old_essential = _essential_populations(before)
    new_essential = _essential_populations(after)

    for title, old_count in sorted(old_essential.items()):
        if title not in new_essential:
            impacts.append(
                CatalogImpact(
                    kind="essential_category_removed",
                    detail=(
                        f"Essential category `{title}` had {old_count} template(s) and is now "
                        "removed, renamed, empty, or no longer marked `isEssential`. Frontends "
                        "may persist or request its generated category identifier."
                    ),
                )
            )

    old_partner_count = _partner_node_count(before)
    new_partner_count = _partner_node_count(after)
    if old_partner_count and not new_partner_count:
        impacts.append(
            CatalogImpact(
                kind="partner_population_removed",
                detail=(
                    f"The `openSource: false` partner-node population fell from "
                    f"{old_partner_count} template(s) to zero, removing the frontend's "
                    "Partner Nodes navigation population."
                ),
            )
        )

    return impacts


def read_index_at_ref(ref: str) -> list[dict]:
    if not ref or ref.startswith("-") or "\0" in ref:
        raise ValueError(f"Invalid git ref: {ref!r}")
    raw = subprocess.check_output(
        ["git", "show", f"{ref}:{INDEX_PATH}"], cwd=REPO_ROOT, text=True
    )
    data = json.loads(raw)
    if not isinstance(data, list):
        raise ValueError(f"{INDEX_PATH} at {ref} is not a list")
    return data


def read_current_index() -> list[dict]:
    data = json.loads((REPO_ROOT / INDEX_PATH).read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"{INDEX_PATH} is not a list")
    return data


def build_report(impacts: list[CatalogImpact]) -> str:
    lines = [
        COMMENT_MARKER,
        "## Consumer-significant catalog change",
        "",
        "Frontend-visible template populations changed. Confirm dependent consumers no longer "
        "request the removed category or population before publishing this catalog.",
        "",
        *[f"- {impact.detail}" for impact in impacts],
        "",
        "<details><summary>Full context for agent readers</summary>",
        "",
        "This is an informational, producer-only diff check. It detects disappearance of "
        "non-empty `isEssential` categories and elimination of all `openSource: false` templates. "
        "It cannot verify frontend versions, persisted user selections, rollout order, or "
        "arbitrary filters. See `scripts/docs/consumer_catalog_changes.md`.",
        "",
        "</details>",
        "",
        "<sub>Generated by `scripts/ci/check_consumer_catalog_changes.py`</sub>",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-ref", required=True)
    parser.add_argument("--comment-file", type=Path)
    parser.add_argument("--github-summary", action="store_true")
    args = parser.parse_args()

    try:
        impacts = detect_impacts(read_index_at_ref(args.base_ref), read_current_index())
    except Exception as exc:
        print(f"Error: consumer catalog change check failed: {exc}", file=sys.stderr)
        return 1

    if not impacts:
        print("No consumer-significant catalog removals detected.")
        return 0

    report = build_report(impacts)
    for impact in impacts:
        print(f"::warning file={INDEX_PATH}::{impact.detail}")
    if args.comment_file:
        args.comment_file.write_text(report, encoding="utf-8")
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if args.github_summary and summary_path:
        Path(summary_path).write_text(
            report.replace(COMMENT_MARKER, "").strip() + "\n", encoding="utf-8"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
