name: Model Analysis Check

on:
  push:
    paths:
      - 'templates/**.json'
      - 'scripts/analyze_models.py'
      - '.github/workflows/model-analysis.yml'
  pull_request:
    paths:
      - 'templates/**.json'
      - 'scripts/analyze_models.py'
      - '.github/workflows/model-analysis.yml'

jobs:
  model-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run model analysis script
        run: python scripts/analyze_models.py 
