name: Sync Templates to GCS

on:
  push:
    branches: [main]
    paths:
      - "templates/**"
  workflow_dispatch:

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Sync templates to GCS
        run: |
          gsutil -m rsync -r -d -c templates/ gs://cloud-workflow-templates/
          echo "Templates synced to GCS bucket successfully"