name: Sync Templates to GCS

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to sync (e.g., 0.1.41). Leave empty to sync current templates to "latest" only.'
        required: false
        type: string

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Sync templates to GCS
        run: |
          UPDATE_LATEST=false

          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION=${{ github.event.release.tag_name }}
            VERSION_DIR=${VERSION#v}
            echo "Release trigger: Syncing templates for version $VERSION_DIR"
            gsutil -m rsync -r -d -c templates/ gs://cloud-workflow-templates/versions/$VERSION_DIR/
            echo "✅ Templates synced to gs://cloud-workflow-templates/versions/$VERSION_DIR/"
            UPDATE_LATEST=true
          elif [ -n "${{ inputs.version }}" ]; then
            VERSION_DIR=${{ inputs.version }}
            echo "Manual trigger: Syncing templates to version $VERSION_DIR"
            gsutil -m rsync -r -d -c templates/ gs://cloud-workflow-templates/versions/$VERSION_DIR/
            echo "✅ Templates synced to gs://cloud-workflow-templates/versions/$VERSION_DIR/"

            CURRENT_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
            if [ "$VERSION_DIR" == "$CURRENT_VERSION" ]; then
              UPDATE_LATEST=true
              echo "This version ($VERSION_DIR) matches current version in pyproject.toml"
            else
              echo "⚠️  Skipping latest update: $VERSION_DIR does not match current version $CURRENT_VERSION"
            fi
          else
            echo "Manual trigger: No version specified, only syncing to latest"
            UPDATE_LATEST=true
          fi

          if [ "$UPDATE_LATEST" == "true" ]; then
            echo "Syncing templates to 'latest' path"
            gsutil -m rsync -r -d -c templates/ gs://cloud-workflow-templates/latest/
            echo "✅ Templates synced to gs://cloud-workflow-templates/latest/"
          else
            echo "⏭️  Skipped updating 'latest' path"
          fi